FROM golang:1.23-alpine AS builder

WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o api-app ./cmd/api/main.go
RUN go build -o worker-app ./cmd/worker/main.go

FROM alpine:latest
WORKDIR /app

COPY --from=builder /build/api-app .
COPY --from=builder /build/worker-app .

CMD ["./api-app"]