FROM golang:1.23-alpine

WORKDIR /build

COPY go.mod go.sum

RUN go mod download

COPY . .

RUN go build -- main ./cmd/api/main.go

FROM alpine:latest 
WORKDIR /root/

COPY --from=builder /build/main .

EXPOSE 8080

CMD ["./main"]